sudo: false
language: ruby
rvm:
- 2.4.3
- 2.3.6
before_install: gem install bundler -v 1.16.1
deploy:
  provider: rubygems
  api_key:
    secure: "a/zKY5ua693JQbj9huBfbAnPFgWtjU3/P0ciAqjE6W0vlhA/yV9O9MwNwum/4wv2rfzSKDXNfSAbdkP6xQ9SwvXlTRwUnUhzf5l9VkC+ksl7G1VlMq802oaNT6NJLW5f04qYdYchrd04YHEfSCFzW5P4zs4C1fiYI8yvFoRhT+y8AU4z7KPBYj7M2qFFgFVJNhvcWxV/sTxJpkZjuQjuQsPOiVIEEmiYF5M81o3jRiT/v+i2+WvG/PrVT3ANzNX9YKrK/3QJNcQDDbUccLMvTM9/Sg/EgHkFf6L6E1GIY2Gn/fhWYtvCy3E+1LgKpLhWB7e3K7Ak/OGUdIsrlvKYlP2Eo13nReMZjEMQ9AHSwVqaoEz3CoZ1UZiPzOCsygkW7E14HD43lNWQI6SLJDumGDFFObRZqn3GkHPTiBsuSHjaJRa69gQsyA+l9IjB1FqxwtutqNnMTyINUBudCHoOYCsgZjJLWEXD/GIW9kDIi6d3VlCAyYlWFeJXx+7h6M8yczdBnMsntfR04MhnSpJS3wWmUa/KZv6ASZcSIA6ZJLJ9AlQhu+Na3WWT89awEAGruemoVgMNFK3d5uLr/dZ5x2QZpN7FdbAbcYSLtgztbfiWwnLprE11BKiu29WEeFj17eT6Uq9gaETCoylPzwCl3ffwzS9XlX2NExIc1pN9eVY="
  gem: ssm_utils
  on:
    tags: true
    repo: dkolb/ssm_utils
